_target_: src.models.tfswa_unet.TFSWAUNet
in_channels: 2
out_channels: 2
depths: [2, 2, 6, 2]
dims: [32, 64, 128, 256]
window_size: 8
shift_size: 4
num_heads: 8

# Memory optimization settings
tsa_chunk_size: 32      # Chunk temporal attention to reduce memory
fsa_chunk_size: 32      # Chunk frequency attention to reduce memory
